### PR TITLE
add containerization files

### PR DESCRIPTION
**Pull request by selaiba**

### CODE REVIEW

**Comment by selaiba** [comment]
Add containerization files

**Comment by gnaegi** [comment]
Hi 

We have no resources at the moment to develop and maintain this and we do not want to have this in our repo unless we can keep it up and running for future releases. 
 
Best would be to offer this in a separate repo where you can maintain it yourself.

**Comment by AntonOfTheWoods** [comment]
Big red flag then...

**Comment by gnaegi** [comment]
> Big red flag then...

I am sure you can enlighten us why this would potentially be a big red flag in general or for you in particular. This is a free downloadable software, you free to maintain containerization for OpenOlat yourself.

**Pull request closed without merging**
