### PR TITLE
Fix mySql database setup script

### PR DESCRIPTION
**Pull request by ShehataIbrahim**
when Importing mysql script an Error is raised
ERROR 1118 (42000) at line 290: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
varchar(255) fields are replaced with text

### CODE REVIEW

**Comment by lainsr** [comment]
Hello

Which encoding did you use for database? utf8mb4?

**Comment by lainsr** [comment]
I fix the issue.

**Comment by ShehataIbrahim** [comment]
> Hello
> 
> Which encoding did you use for database? utf8mb4? And which version of MySQL?

utf8

**Comment by ShehataIbrahim** [comment]
> I fix the issue.

would you please review my change and clarify if it is a valid fix?

**Comment by lainsr** [comment]
I fix your issue but not with your patch. You cannot simply replace all VARCHAR(255) with TEXT. I replace only selected ones with TEXT(255). There are light differences between TEXT and VARCHAR and, as we support other databases as well, I want to reduce the differences between the schema for every database as much as possible.

But thank you for the patch and to make us aware of the issue.

**Comment by lainsr** [comment]
This is the change: https://github.com/OpenOLAT/OpenOLAT/commit/a32258608b3348fadf559abab0737c74311fd4a6

I'm a bit surprised that you have an issue with utf8, it's the encoding I use daily without a problem. Usually this happens with encoding like utf8mb4, utf16 or utf32.

**Pull request closed without merging**
