### PR TITLE
Clean up selenium methods a bit: DRY, remove unused methods

### PR DESCRIPTION
**Pull request by tomgross**
This PR does the following:

- Remove redundant methods (DRY)
- Fix obvious JavaDoc mistakes
- Remove obsolete Browser (Firefox) check. This is actually a w3c-capability check. Since chromedriver 75 w3c is enabled by default and selenium tests fail if this condition is not removed.

### CODE REVIEW

**Comment by lainsr** [comment]
> This PR does the following:
> 
> * Remove redundant methods (DRY)
> * Fix obvious JavaDoc mistakes
> * Remove obsolete Browser (Firefox) check. This is actually a w3c-capability check. Since Which selenium test fails? We run them every night with Firefox and Chrome without problems. And my Firefox checks are mostly to improve the reliability of tests. Did you test the whole suit against Firefox and Chrome several times (5 - 10 times) on Linux? The Firefox driver is still buggy in some places.

**Comment by tomgross** [comment]
They fail with Chrome headless:

```
3199074 [ERROR] Errors:
3199074 [ERROR] ImsQTI21EditorTest.qti21EditorHotspot_multipleChoice:1179 » MoveTargetOutOfBounds
3199074 [ERROR] ImsQTI21EditorTest.qti21EditorHotspot_singleChoice:998 » MoveTargetOutOfBounds
3199074 [ERROR] ImsQTI21EditorTest.qti21EditorNegativePoints:3429 » MoveTargetOutOfBounds move...
3199074 [INFO]
3199074 [ERROR] Tests run: 153, Failures: 0, Errors: 3, Skipped: 0
3199074 [INFO]
```

**Comment by tomgross** [comment]
This is the configuration: 

`-Dtest.env.webdriver.browser=chromeheadless -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dwebdriver.chrome.arguments='--disable-dev-shm-usage --disable-extensions --disable-gpu --no-sandbox' -Ptomcat`

**Comment by lainsr** [comment]
Ok, I don't use or test with Chrome headless (because no real human use it). I will take a look at it.

**Comment by lainsr** [comment]
The check for the Firefox Browser is not obsolete, it's a performance optimisation as Chrome doesn't need this step and I hope to remove it in the future for both browsers.

And you remove the closeError which is quit useful (I need it at least during development and in selectus).

**Pull request merged**
