### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by tomgross**
This PR removes code obviously never used.

### CODE REVIEW

**Comment by lainsr** [comment]
Obviously you don't have all our code. We share the OpenOlat code base with some not open source very specific extensions and with selectus. Every time you delete something, I need to check that you didn't break something in 3 different repositories.

**Comment by tomgross** [comment]
Oh no, I'm sorry for that.

Maybe it would help to explicitly comment these methods, to avoid confusion?

**Comment by lainsr** [comment]
Two remarks:

- Unused imports are errors for us.
- In the future, please don't beautify the Window.class, this is the most important and probably the most complex class of OpenOlat and I want to have a history as clean as possible with only the requisite changes need by new features

**Comment by tomgross** [comment]
@lainsr Thanks for the merge and thanks for the feedback. I'll keep that in mind.

**Pull request merged**
